/**
* Please DONOT change this file, it is auto generated by maven ant task.
*/
package com.openthinks.easyiot.core;

public interface Static{
	public static final String MYBATIS_CORE_PACKAGE="com.openthinks.easyiot.core";
	public static final String MYBATIS_CORE_MAPPER_PACKAGE="com.openthinks.easyiot.core.mapper";
	public static final String MYBATIS_CORE_MODEL_PACKAGE="com.openthinks.easyiot.core.model";
}